### ISSUE TITLE
offline LLM

### ISSUE THREAD

**Issue by CRiMSONxx** [lokeshparihar100/GenAI_ChatBot#1]
hey i recently learned that you can use privategpt (uses gpt4all, offline), not as good as openai i know, but its enough, maybe you can integrate them so you have choice to use openai or custom offline LLM (using you computer resource).

cheers

**Comment by lokeshparihar100** [comment]
@CRiMSONxx  Thanks for letting me know. But I have designed this project to use OpenAI API. I'll create another project which will use private GPT: https://github.com/imartinez/privateGPT

**Comment by lokeshparihar100** [comment]
@CRiMSONxx Thanks for letting me know. But I have designed this project to use OpenAI API. I'll create another project which will use private GPT: https://github.com/imartinez/privateGPT

**Comment by lokeshparihar100** [comment]
@CRiMSONxx Thanks for letting me know. But I have designed this project to use OpenAI API. I'll create another project which will use private GPT: https://github.com/imartinez/privateGPT
